# Generated by Django 5.0.3 on 2024-03-28 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address_line2',
        ),
    ]
