# Generated by Django 5.0.3 on 2024-03-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_address_line_userprofile_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='preferred_name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
